### PR TITLE
PIPE-1171: fix all jobs must match agent tags bug + introduce controller ID

### LINKED ISSUE #625: [BUG] All job tags must match agent tags
## Describe the bug

This PR (https://github.com/buildkite/agent-stack-k8s/pull/596) changed how agent targeting works. Now, a job's tags must match ALL the agent's tags. 

This behaviour is not the same as how [buildkite/agent](https://github.com/buildkite/agent) works, where it only has to match at least 1 of the agent's tags for it to be picked up.

## To Reproduce

Appears on version >0.28.0 from PR https://github.com/buildkite/agent-stack-k8s/pull/596

## Expected behavior

Jobs request a list of tags, and it will run on agents matching them, but necessarily all of them.

## Environment
- agent-stack-k8s version: [e.g., v1.0.0] 0.28.1
- Kubernetes version: [e.g., v1.24.0] 1.33.0
- Deployment method: [e.g., Helm chart, manual manifest] helm

## Logs
```
job tags do not match expected tags in configuration, skipping...
```

## Additional context

N/A

### PR DESCRIPTION
**Pull request by zhming0**
Solves #625

This PR first of all fixes #625, effectively reverting #596, as the fix was addressing one issue, introducing another.

As a replacement, this PR changed controller so it stops using tags to find correct pods to monitor. Using tags to match pods has a few issue: 
- first and foremost: tags can changes between restart.
- tags matching logic is much more difficult to express using k8s. 
  - Previously the controller is finding pods that has identical tags with controller tags. 
  - But not all pods will have the identical tags -> so this is clearly wrong. 

This PR proposed a new `ID` config variable as an stable identifier for controller, the `ID` will be set by helm during install, otherwise it's optional.

### CODE REVIEW

File: internal/controller/agenttags/tags.go [hunk 1]
```diff
@@ -88,24 +88,21 @@ func LabelsFromTags(tags []string) (map[string]string, []error) {
...
 // See https://buildkite.com/docs/agent/v3/cli-start#agent-targeting
 
 func MatchJobTags(agentTags, jobTags map[string]string) bool {
-	if len(agentTags) != len(jobTags) {
-		return false
-	}
-	for k, v := range agentTags {
-		jobTagValue, exists := jobTags[k]
+	for k, jobTagValue := range jobTags {
+		agentTagValue, exists := agentTags[k]
```
Comment (DrJosh9000) [inline internal/controller/agenttags/tags.go:101]: This looks like a rollback of #596 - is the bug described in #596 fixed some other way? 

> This was allowing scheduled jobs with only a matching queue tag to be created as a K8s Job. This then prevented the informer from matching the Labels of these Jobs and the controller was left with an infinitely increasing number of running jobs.

Perhaps we should:

* make the Informer listen for objects matching fewer labels 
* put the necessary tag/label matching in our code

**Review by DrJosh9000 — CHANGES_REQUESTED** [review]

File: internal/controller/agenttags/tags.go (hunk 1 above)
Comment (zhming0) [reply internal/controller/agenttags/tags.go:101]: @DrJosh9000 I've re-implemented this PR. Another look please 🙏🏿

File: internal/controller/controller.go [hunk 2]
```diff
@@ -238,26 +239,28 @@ func Run(
...
-	for l, v := range labelsFromTags {
-		hasLabel, err := labels.NewRequirement(l, selection.Equals, []string{v})
+	if id != "" {
+		hasRightId, err := labels.NewRequirement(config.ControllerIDLabel, selection.Equals, []string{id})
+		if err != nil {
+			return nil, fmt.Errorf("failed to build controller id label selector for job manager: %w", err)
+		}
+		requirements = append(requirements, *hasRightId)
+	} else {
+		// In the case when Id isn't specified, we shouldn't try to monitor those jobs that has id label.
```
Comment (DrJosh9000) [inline internal/controller/controller.go]: Consider adding a similar comment about how the Helm chart set it here:
 ```suggestion
		// In the case when ID isn't specified, we shouldn't try to monitor those jobs that has id label.
		// Note that ID is set by the Helm chart, so this should not happen in usual installations.
```

File: internal/controller/scheduler/scheduler.go [hunk 3]
```diff
@@ -53,6 +53,7 @@ var (
 
 type Config struct {
 	Namespace                      string
+	Id                             string
```
Comment (DrJosh9000) [inline internal/controller/scheduler/scheduler.go]: As for config/config.go
```suggestion
	ID                             string
```

File: internal/controller/config/config.go [hunk 4]
```diff
@@ -56,6 +57,12 @@ type Config struct {
 	WorkQueueLimit           int           `json:"work-queue-limit"         validate:"omitempty"`
 	// Agent endpoint is set in agent-config.
 
+	// Id is an optional uniquely ID string for the controller.
+	// This is useful when running multiple bk k8s controllers within the same k8s namespace.
+	// So the controller can target the correct pods.
+	// By default, if helm is used to install, this will be set as helm release full name.
+	Id string `json:"id" validate:"omitempty"`
```
Comment (DrJosh9000) [inline internal/controller/config/config.go]: I typically spell it `ID` rather than `Id` (see also https://google.github.io/styleguide/go/decisions#initialisms)
```suggestion
	ID string `json:"id" validate:"omitempty"`
```

File: internal/controller/controller.go [hunk 5]
```diff
@@ -238,26 +239,29 @@ func Run(
...
 	hasUUID, err := labels.NewRequirement(config.UUIDLabel, selection.Exists, nil)
 	if err != nil {
 		return nil, fmt.Errorf("failed to build uuid label selector for job manager: %w", err)
 	}
 	requirements = append(requirements, *hasUUID)
 
-	for l, v := range labelsFromTags {
-		hasLabel, err := labels.NewRequirement(l, selection.Equals, []string{v})
+	if id != "" {
+		hasRightId, err := labels.NewRequirement(config.ControllerIDLabel, selection.Equals, []string{id})
```
Comment (DrJosh9000) [inline internal/controller/controller.go]:
```suggestion
		hasRightID, err := labels.NewRequirement(config.ControllerIDLabel, selection.Equals, []string{id})
```

File: internal/controller/controller.go [hunk 6]
```diff
@@ -238,26 +239,29 @@ func Run(
...
+		if err != nil {
+			return nil, fmt.Errorf("failed to build controller id label selector for job manager: %w", err)
+		}
+		requirements = append(requirements, *hasRightId)
```
Comment (DrJosh9000) [inline internal/controller/controller.go]:
```suggestion
		requirements = append(requirements, *hasRightID)
```

File: internal/controller/controller.go [hunk 7]
```diff
@@ -238,26 +239,29 @@ func Run(
...
+	} else {
+		// In the case when ID isn't specified, we shouldn't try to monitor those jobs that has ID label.
+		// Note that ID is set by the Helm chart, so this should not happen in usual installations.
+		noId, err := labels.NewRequirement(config.ControllerIDLabel, selection.DoesNotExist, nil)
```
Comment (DrJosh9000) [inline internal/controller/controller.go]:
```suggestion
		noID, err := labels.NewRequirement(config.ControllerIDLabel, selection.DoesNotExist, nil)
```

File: internal/controller/controller.go [hunk 8]
```diff
@@ -238,26 +239,29 @@ func Run(
...
 		if err != nil {
-			return nil, fmt.Errorf("failed create label selector agent tag: %w", err)
+			return nil, fmt.Errorf("failed to build controller id label selector for job manager: %w", err)
 		}
-		requirements = append(requirements, *hasLabel)
+		requirements = append(requirements, *noId)
```
Comment (DrJosh9000) [inline internal/controller/controller.go]:
```suggestion
		requirements = append(requirements, *noID)
```

File: internal/controller/scheduler/scheduler_test.go [hunk 9]
```diff
@@ -539,6 +540,9 @@ func TestBuild(t *testing.T) {
 
 	require.Len(t, kjob.Spec.Template.Spec.Containers, 3)
 
+	controllerIdLabel := kjob.Labels["buildkite.com/controller-id"]
+	assert.Equal(t, controllerIdLabel, "controller-1")
```
Comment (DrJosh9000) [inline internal/controller/scheduler/scheduler_test.go]:
```suggestion
	controllerIDLabel := kjob.Labels["buildkite.com/controller-id"]
	assert.Equal(t, controllerIDLabel, "controller-1")
```

**Review by DrJosh9000 — APPROVED** [review]
LGTM!

My remaining suggestions are just quick follow-ons about `ID`.

---

Do you have any ideas for how we could write a test to cover the issue originally fixed by #596?

**Comment by zhming0** [comment]
@DrJosh9000 that's good question. I could have a misunderstood the symptom of #596, I thought our `TestMaxInFlightLimited` should catch the issue but apparently `TestMaxInFlightLimited` was added long before the issue exist. 

Do you have more contexts? (happy to move this chat to slack if you prefer too)

As for this PR, I think the change is sound, I will merge this first and maybe come back with a test later.
