### PR TITLE
Don't schedule using stale job info

### LINKED ISSUE #382: Controller keeps scheduling Pods from a cancelled Build
Steps to reproduce:

1. Set up buildkite/agent-stack-k8s with max-in-flight: 2
1. Push a new commit to an open PR which, it triggers 10 new jobs, controller schedules 2 Pods at a time respecting `max-in-flight: 2`
1. Cancel the build in Buildkite UI / API, all 10 new jobs display as Cancelled in Buildkite UI
1. Observe controller still scheduling Pods for that build flooding the K8S cluster (kubectl describe pod shows BUILDKITE_COMMIT which is cancelled) and preventing other Jobs from being handled

Environment:

- AWS EKS v1.25
- buildkite/agent-stack-k8s v0.15.0

### PR DESCRIPTION
**Pull request by DrJosh9000**
### Why
Fixes #382 

### What
Change the `Handler` interface to accept a new `Job` that includes a channel that is closed when the job information becomes stale. This can be used to time out in the limiter waiting for a token to become available. That way, stale jobs won't be given to the scheduler.

### CODE REVIEW

File: internal/controller/monitor/monitor.go [hunk 1]
```diff
@@ -32,8 +32,16 @@ type Config struct {
 	Tags            []string
 }
 
+type Job struct {
+	// The job information.
+	*api.CommandJob
+
+	// Closed when the job information becomes stale.
+	StaleCh <-chan struct{}
```
Comment (artem-zinnatullin) [inline internal/controller/monitor/monitor.go:40]: Hm, I thought the fix would be to double-check the cancellation/etc state of the Job/Build before actually scheduling it onto K8S

Having a callback (Channel) when information becomes stale seems like a much more complicated way to achieve that with unclear benefits and requires running a polling loop to keep the channel updated which will load up Buildkite backend quite a lot with these polling checks…

Sorry I'm not very proficient with Golang, can you please help me understand why this approach is better? Thanks!

File: internal/controller/scheduler/limiter.go [hunk 2]
```diff
@@ -93,7 +92,8 @@ func (l *MaxInFlightLimiter) Create(ctx context.Context, job *api.CommandJob) er
 		return nil
 	}
 
-	// Block until there's a token in the bucket.
+	// Block until there's a token in the bucket, or the job information becomes
```
Comment (artem-zinnatullin) [inline internal/controller/scheduler/limiter.go:95]: I think the intent of the code here doesn't really align with the comment

To block until something is stale is quite meaningless. Perhaps something like this wording could be used
```suggestion
	// Block until there's a token in the bucket, or cancel if the job information becomes stale.
```

File: internal/controller/monitor/monitor.go (hunk 1 above)
Comment (DrJosh9000) [reply internal/controller/monitor/monitor.go:40]: If there was no limiter in place then Buildkite would receive a query every `PollInterval` for jobs to run (call this the query loop), and monitor would loop over the result (the inner loop), calling `handler.Create` for each of them. 

In the previous PR on the limiter, I changed how the limiter worked to introduce blocking on the "token bucket", but this causes the bug: a job that was returned from the query a long time ago could be next in the inner loop in the Monitor around `handler.Create`, so that when the limiter can finally get a token, the job could now be cancelled.

With the `StaleCh` approach, the limiter can block until either there's a token, or the job information is stale. If it's stale, then the limiter shouldn't pass the job onto the scheduler and it can return early. Then the query loop can wait until the next `PollInterval` to run the main query.

To double-check the cancellation state of the job before passing it on to the scheduler, or double-checking within scheduler, would mean making another query to Buildkite at that point. 

So while I think my approach doesn't look particularly clean (I could probably make it look nicer), it does avoid the extra query.

Comment (artem-zinnatullin) [reply internal/controller/monitor/monitor.go:40]: I see, so the idea is to keep the query loop as the main source of truth for up-to-date data and avoid creating a separate code path for explicit job state refresh? Sounds reasonable!

I guess coming from Reactive Streams I'd expect one Channel to be enough to either provide a valid object or indicate cancellation/stale by closing it, The "query loop" logic would then be distributing the updates about jobs to the interested channels or closing those channels when job is cancelled.

Your approach seems to solve that so there is no issue, just speaking out loud :)

**Review by artem-zinnatullin — APPROVED** [review]

**Review by wolfeidau — APPROVED** [review]
Tough problem.
